config/routes.rb
Rails.application.routes.draw do
  root to: "reports#index"
  resources :reports, only: [:new, :create, :index, :show]
end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :service_reports
  attr_accessor :file

  validates :title, presence: true
  validates :file, presence: true
end

app/models/service_report.rb
class ServiceReport < ActiveRecord::Base
  belongs_to :report
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    excel_file = params[:report][:file].tempfile if @report.valid?

    if @report.save
      ReportsImporter.handle_file(@report, excel_file)
      redirect_to @report, notice: "Report created successfully!"
    else
      render :new, alert: "Please check the errors below"
    end
  end

  def show
    @report = Report.find(params[:id])
    @service_reports = @report.service_reports
  end

  private

  def report_params
    params.require(:report).permit(:title, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ExcelImport
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if notice
      %p.notice= notice

    .container
      = yield

app/views/reports/index.html.haml
%section.main
  %h2 Reports list:

  %ul
    - @reports.each do |report|
      %li= link_to report.title, report

  %p
    = link_to 'Add new report', new_report_path

app/views/reports/new.html.haml
%section.main
  %h2 New report

  = simple_form_for @report do |f|
    = f.input :title, label: "Title of the report"
    = f.input :file, as: :file, label: "Select Excel file"
    = f.button :submit, label: "Create new report"

app/views/reports/show.html.haml
%table
  %caption= @report.title
  %tr
    %th Month
    %th Number of total services

  - @service_reports.each do |item|
    %tr
      %td= Date::MONTHNAMES[item.month]
      %td= item.total_services